service: gcp-webhooks

provider:
  name: google
  stage: dev
  runtime: nodejs16
  region: us-central1
  project: webhook-proj
  credentials: ~/.gcloud/ambient-sphere.json

frameworkVersion: '3'

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  producer:
    handler: http
    events:
      - http: path
  consumer:
   handler: event
   events:
     - event:
         eventType: providers/cloud.pubsub/eventTypes/topic.publish
         resource: 'projects/${self:provider.project, ""}/topics/stripe-transaction'
